### ISSUE TITLE
Colab crashes on images generation

### ISSUE THREAD

**Issue by tempdeltavalue** [robvanvolt/DALLE-models#10]
generating images for - the grand canyon with snow on it. snow located on the grand canyon. a snowy grand canyon.:   0% 0/1 [00:00<?, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/generate.py", line 116, in <module>
    output = dalle.generate_images(text_chunk, filter_thres = args.top_k)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 42, in inner
    out = fn(model, *args, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 480, in generate_images
    logits = self(text, image, mask = mask)[:, -1, :]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/dalle_pytorch.py", line 552, in forward
    out = self.transformer(tokens)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/transformer.py", line 142, in forward
    return self.layers(x, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/reversible.py", line 156, in forward
    out =  _ReversibleFunction.apply(x, blocks, args)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/reversible.py", line 113, in forward
    x = block(x, **kwarg)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/reversible.py", line 65, in forward
    y1 = x1 + self.f(x2, record_rng=self.training, **f_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/reversible.py", line 40, in forward
    return self.net(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/transformer.py", line 53, in forward
    return self.fn(x, **kwargs) * self.scale
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/transformer.py", line 62, in forward
    return self.fn(self.norm(x), **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/dalle-pytorch-pretrained/DALLE-pytorch/dalle_pytorch/attention.py", line 362, in forward
    out = self.attn_fn(q, k, v, attn_mask = attn_mask, key_padding_mask = key_pad_mask)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/sparse_self_attention.py", line 152, in forward
    attn_output_weights = sparse_dot_sdd_nt(query, key)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 745, in __call__
    time_db)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 549, in forward
    c_time)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/matmul.py", line 188, in _sdd_matmul
    _sparse_matmul.sdd_cache[key] = triton.kernel(
AttributeError: module 'triton' has no attribute 'kernel'

**Comment by johnpaulbin** [comment]
Fixed
